apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-reader-rolebinding
  namespace: production
subjects:
- kind: ServiceAccount
  name: prod-reader
  namespace: production
roleRef:
  kind: Role
  name: prod-reader-role
  apiGroup: rbac.authorization.k8s.io
