apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:alpine
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: my-db-credentials
          key: username
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: my-db-credentials
          key: password
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: my-api-credentials
          key: api-key
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo 'Env variables loaded'; sleep 30; done"]
  restartPolicy: Never
