apiVersion: v1
kind: Pod
metadata:
  name: secure-comm
spec:
  containers:
  - name: curl
    image: curlimages/curl:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do curl -k -s http://vault.vault.svc.cluster.local:8200/v1/sys/health && echo 'Vault OK'; sleep 60; done"]
  restartPolicy: Never
