apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:alpine
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/mysecrets
      readOnly: true
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo 'Pod running...'; sleep 30; done"]
  volumes:
  - name: secret-volume
    secret:
      secretName: my-db-credentials
  restartPolicy: Never
