apiVersion: v1
kind: Pod
metadata:
  name: vault-app
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "myapp"
    vault.hashicorp.com/agent-inject-secret-db: "secret/data/myapp/db"
    vault.hashicorp.com/agent-inject-template-db: |
      {{- with secret "secret/data/myapp/db" -}}
      export DB_USER="{{ .Data.data.username }}"
      export DB_PASS="{{ .Data.data.password }}"
      export DB_HOST="{{ .Data.data.host }}"
      export DB_PORT="{{ .Data.data.port }}"
      {{- end }}
    vault.hashicorp.com/agent-inject-secret-api: "secret/data/myapp/api"
    vault.hashicorp.com/agent-inject-template-api: |
      {{- with secret "secret/data/myapp/api" -}}
      export API_KEY="{{ .Data.data.key }}"
      export API_SECRET="{{ .Data.data.secret }}"
      export API_ENDPOINT="{{ .Data.data.endpoint }}"
      {{- end }}
spec:
  serviceAccountName: vault-auth
  containers:
  - name: app
    image: nginx:alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo 'App running with Vault secrets'; sleep 30; done"]
