apiVersion: v1
kind: Pod
metadata:
  name: baseline-allowed
  namespace: sec-demo
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80
    securityContext:
      runAsNonRoot: false
      allowPrivilegeEscalation: false
