apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web
  namespace: shop-app
  labels:
    app: frontend-web
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      labels:
        app: frontend-web
        tier: frontend
    spec:
      containers:
      - name: web
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: API_ENDPOINT
          value: "http://backend-service:8080"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: shop-app
spec:
  selector:
    app: frontend-web
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
