apiVersion: v1
kind: Pod
metadata:
  name: restricted-compliant
  namespace: restricted-demo
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
    runAsNonRoot: true
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 8080
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault
    volumeMounts:
    - name: tmp
      mountPath: /tmp
      readOnly: false
    - name: var-cache
      mountPath: /var/cache/nginx
      readOnly: false
    - name: var-run
      mountPath: /var/run
      readOnly: false
  volumes:
  - name: tmp
    emptyDir: {}
  - name: var-cache
    emptyDir: {}
  - name: var-run
    emptyDir: {}

