apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: isolate-compromised-pods
  namespace: testing
spec:
  podSelector:
    matchLabels:
      status: infected
  policyTypes:
  - Ingress
  - Egress
  ingress: []
  egress:
  - to: []
    ports:
    - protocol: UDP
      port: 53
