apiVersion: v1
kind: Pod
metadata:
  name: vulnerable-pod
  namespace: threat-modeling-lab
spec:
  containers:
  - name: vulnerable-container
    image: ubuntu:20.04
    command: ["/bin/sleep","3600"]
    securityContext:
      privileged: true
      runAsUser: 0
      capabilities:
        add:
        - SYS_ADMIN
        - NET_ADMIN
    volumeMounts:
    - name: host-root
      mountPath: /host
  volumes:
  - name: host-root
    hostPath:
      path: /
  serviceAccountName: default
